CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) NOT NULL,
  avatar_url TEXT,
  role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  email_verified_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS profiles (
  id CHAR(36) PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  avatar_url TEXT,
  date_of_birth DATE,
  gender ENUM('male', 'female', 'other') NULL,
  height_cm DECIMAL(5,2),
  current_weight_kg DECIMAL(5,2),
  target_weight_kg DECIMAL(5,2),
  activity_level ENUM('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extremely_active') DEFAULT 'moderately_active',
  goal_type ENUM('lose_weight', 'gain_weight', 'maintain_weight', 'eat_healthy') DEFAULT 'eat_healthy',
  target_calories INT,
  target_protein_g DECIMAL(6,2),
  target_carbs_g DECIMAL(6,2),
  target_fat_g DECIMAL(6,2),
  target_fiber_g DECIMAL(6,2),
  target_water_ml INT DEFAULT 2000,
  diet_type VARCHAR(20) DEFAULT 'omnivore',
  allergies JSON,
  cuisine_preferences JSON,
  weekly_weight_goal_kg DECIMAL(4,2),
  target_date DATE,
  bmr DECIMAL(8,2),
  tdee DECIMAL(8,2),
  onboarding_completed BOOLEAN DEFAULT FALSE,
  streak_days INT DEFAULT 0,
  last_log_date DATE,
  total_points INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_profiles_user FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
