CREATE TABLE IF NOT EXISTS food_database (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  name_en VARCHAR(200),
  category ENUM('breakfast', 'lunch', 'dinner', 'snack', 'drink', 'supplement', 'other') NOT NULL,
  sub_category VARCHAR(50),
  serving_unit VARCHAR(50) DEFAULT 'gram',
  serving_size_g DECIMAL(8,2) DEFAULT 100,
  calories DECIMAL(8,2) NOT NULL,
  protein_g DECIMAL(8,2) DEFAULT 0,
  carbohydrates_g DECIMAL(8,2) DEFAULT 0,
  fat_g DECIMAL(8,2) DEFAULT 0,
  fiber_g DECIMAL(8,2) DEFAULT 0,
  sugar_g DECIMAL(8,2) DEFAULT 0,
  sodium_mg DECIMAL(8,2) DEFAULT 0,
  cholesterol_mg DECIMAL(8,2) DEFAULT 0,
  vitamin_a_mcg DECIMAL(8,2) DEFAULT 0,
  vitamin_b1_mg DECIMAL(8,2) DEFAULT 0,
  vitamin_b6_mg DECIMAL(8,2) DEFAULT 0,
  vitamin_b12_mcg DECIMAL(8,2) DEFAULT 0,
  vitamin_c_mg DECIMAL(8,2) DEFAULT 0,
  vitamin_d_mcg DECIMAL(8,2) DEFAULT 0,
  vitamin_e_mg DECIMAL(8,2) DEFAULT 0,
  calcium_mg DECIMAL(8,2) DEFAULT 0,
  iron_mg DECIMAL(8,2) DEFAULT 0,
  zinc_mg DECIMAL(8,2) DEFAULT 0,
  magnesium_mg DECIMAL(8,2) DEFAULT 0,
  potassium_mg DECIMAL(8,2) DEFAULT 0,
  image_url TEXT,
  is_indonesian BOOLEAN DEFAULT TRUE,
  is_custom BOOLEAN DEFAULT FALSE,
  is_public BOOLEAN DEFAULT TRUE,
  created_by CHAR(36) NULL,
  barcode VARCHAR(50),
  tags JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FULLTEXT KEY idx_food_database_search (name, name_en, sub_category),
  INDEX idx_food_database_category (category),
  INDEX idx_food_database_is_public (is_public),
  CONSTRAINT fk_food_database_creator FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
