CREATE TABLE IF NOT EXISTS food_logs (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  food_id CHAR(36) NULL,
  food_name VARCHAR(200) NOT NULL,
  meal_type ENUM('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', 'late_snack') NOT NULL,
  log_date DATE NOT NULL DEFAULT (CURRENT_DATE),
  log_time TIME DEFAULT (CURRENT_TIME),
  serving_amount DECIMAL(8,2) NOT NULL DEFAULT 1,
  serving_unit VARCHAR(50) DEFAULT 'porsi',
  serving_size_g DECIMAL(8,2),
  calories DECIMAL(8,2) NOT NULL,
  protein_g DECIMAL(8,2) DEFAULT 0,
  carbohydrates_g DECIMAL(8,2) DEFAULT 0,
  fat_g DECIMAL(8,2) DEFAULT 0,
  fiber_g DECIMAL(8,2) DEFAULT 0,
  sugar_g DECIMAL(8,2) DEFAULT 0,
  sodium_mg DECIMAL(8,2) DEFAULT 0,
  photo_url TEXT,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_food_logs_user_date (user_id, log_date),
  INDEX idx_food_logs_meal_type (meal_type),
  CONSTRAINT fk_food_logs_user FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE,
  CONSTRAINT fk_food_logs_food FOREIGN KEY (food_id) REFERENCES food_database(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS weight_logs (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  weight_kg DECIMAL(5,2) NOT NULL,
  body_fat_percentage DECIMAL(5,2),
  muscle_mass_kg DECIMAL(5,2),
  waist_cm DECIMAL(5,2),
  chest_cm DECIMAL(5,2),
  hip_cm DECIMAL(5,2),
  arm_cm DECIMAL(5,2),
  thigh_cm DECIMAL(5,2),
  bmi DECIMAL(5,2),
  bmi_category VARCHAR(20),
  photo_url TEXT,
  notes TEXT,
  log_date DATE NOT NULL DEFAULT (CURRENT_DATE),
  log_time TIME DEFAULT (CURRENT_TIME),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY idx_weight_logs_user_date (user_id, log_date),
  INDEX idx_weight_logs_user_id (user_id),
  CONSTRAINT fk_weight_logs_user FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meal_schedules (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  meal_type ENUM('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', 'late_snack') NOT NULL,
  scheduled_time TIME NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  reminder_enabled BOOLEAN DEFAULT TRUE,
  reminder_minutes_before INT DEFAULT 15,
  custom_message TEXT,
  days_of_week JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY idx_meal_schedules_user_type (user_id, meal_type),
  CONSTRAINT fk_meal_schedules_user FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS meal_plans (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  plan_name VARCHAR(100),
  plan_date DATE NOT NULL,
  meal_type ENUM('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', 'late_snack') NOT NULL,
  food_id CHAR(36) NULL,
  food_name VARCHAR(200) NOT NULL,
  serving_amount DECIMAL(8,2) DEFAULT 1,
  serving_unit VARCHAR(50) DEFAULT 'porsi',
  target_calories DECIMAL(8,2),
  target_protein_g DECIMAL(8,2),
  target_carbs_g DECIMAL(8,2),
  target_fat_g DECIMAL(8,2),
  is_completed BOOLEAN DEFAULT FALSE,
  completed_at DATETIME NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_meal_plans_user_date (user_id, plan_date),
  CONSTRAINT fk_meal_plans_user FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE,
  CONSTRAINT fk_meal_plans_food FOREIGN KEY (food_id) REFERENCES food_database(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
